name: "[PUSH] Create Package"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "force-app/**"
jobs:
  create-package:
    name: Run Package Creation
    uses: navikt/crm-workflows-base/.github/workflows/packageCreate.yml@830a9b2aa02dbf273c36c786f45dba9ff5b963ab
    permissions:
      contents: write
    secrets: inherit
